# The Top 10'000 Books from Goodreads on Kaggle

In [2]:
import pandas as pd
import numpy as np
import requests
import re
import json

Source of data can be found in the source.txt file. Very useful information is in the latter two data sets, they have a bug, am working on fixing it. Data sets 1-5 will require some work merging and organizing.

### Data Set "Books"

In [3]:
data1 = pd.read_csv(r'data/books.csv')
books = pd.DataFrame(data1)
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

### Data Set "Book Tags"

In [4]:
data2 = pd.read_csv(r'data/book_tags.csv')
book_tags = pd.DataFrame(data2)
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

### Data Set "Tags"

In [5]:
data3 = pd.read_csv(r'data/tags.csv')
tags = pd.DataFrame(data3)
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [6]:
tags_list = list(tags.tag_name.unique())
tags_list # this is a mess

['-',
 '--1-',
 '--10-',
 '--12-',
 '--122-',
 '--166-',
 '--17-',
 '--19-',
 '--2-',
 '--258-',
 '--3-',
 '--33-',
 '--4-',
 '--5-',
 '--51-',
 '--6-',
 '--62-',
 '--8-',
 '--99-',
 '--available-at-raspberrys--',
 '-2001--',
 '-calif--',
 '-d-c--',
 '-dean',
 '-england-',
 '-fiction',
 '-fictional',
 '-fictitious',
 '-football-',
 '-george',
 '-gr-',
 '-history',
 '-imaginary',
 '-italy-',
 '-la--',
 '-los',
 '-mass--',
 '-murder-',
 '-n-y--',
 '-non-poetry-',
 '-performing',
 '-post',
 '-psychology-',
 '-read',
 '-single',
 '-specific',
 '-television',
 '0',
 '0-0-0-0cant-find',
 '0-0-bingo',
 '0-4-star-rating',
 '0-a-find-2016-summer-00',
 '0-all2',
 '0-best-picture-younger',
 '0-boxed',
 '0-c',
 '0-eric-s-books',
 '0-house-lbkc',
 '0-kindle',
 '0-love-funny',
 '0-made-me-cry-moved-me',
 '0-nonfiction',
 '0-owned',
 '0-paperback',
 '0-pgs-200-to-299',
 '0-physical-own',
 '0-plays',
 '0-plc',
 '0-tbr-axz-usa',
 '00-exploring-1',
 '00-graphic-novels-read',
 '00-in-class',
 '00-to-read-00',
 '00-to-read-02',
 '0000',
 '0000-to-buy',
 '00000',
 '0000_notverified',
 '000src-su-25-11-3-x',
 '000src-w-15-01-i-me-mine',
 '001-150-pages',
 '001-ebook',
 '002-read-cookbook',
 '002-une-bonne-selection',
 '007',
 '008-strategy',
 '01',
 '01-alphabet-authors',
 '01-distopias',
 '01-ecookbooks',
 '01-folklore',
 '01-irl-bookshelf-comics',
 '01-mine',
 '01-words',
 '016-sam-j-miller',
 '01_best-books',
 '02-500-750',
 '02-black-exp',
 '02-fantasy',
 '02-folklore',
 '02-to-read-speculative-fiction',
 '02-words-sb',
 '0201-0300-pages',
 '029-نجيب-محفوظ',
 '03-20thcentury-american-lit',
 '03-classic-fairy',
 '03-classic-fairy-tales',
 '03-informational',
 '03-sami-lukematta',
 '03-star',
 '03-words-sc',
 '04-babies-and-toddlers',
 '04-caldecott',
 '04-easy-to-read-books',
 '04-preschoolers',
 '04-realistic-fiction',
 '04-star',
 '04-stars',
 '0471239720',
 '05-high-fantasy',
 '05ip9hg',
 '06-not-my-kind-of-book',
 '06-traditional',
 '07-hist-fiction',
 '07-modern-fantasy',
 '07-まんが-ほか',
 '08-childhood-ya',
 '08-realistic-fiction',
 '08-words-ns',
 '0fiction-incomplete-series',
 '0nonfiction',
 '0want-it',
 '0wn',
 '0wned',
 '1',
 '1-0-1-9',
 '1-000-books-before-kindergarten',
 '1-1',
 '1-10',
 '1-12',
 '1-2',
 '1-4',
 '1-5-stars-all-genres',
 '1-ab-a-a-bookcount-5',
 '1-and-2-stars',
 '1-art-modern',
 '1-at-school',
 '1-ax-a-a-bookscouter-1',
 '1-b',
 '1-books-i-own',
 '1-bx-libraries',
 '1-children-ya',
 '1-chronicles',
 '1-classic-literature',
 '1-favorites',
 '1-fiction',
 '1-gen-lit',
 '1-have',
 '1-in-3',
 '1-in-series',
 '1-jordan-peterson',
 '1-kindle',
 '1-ladies-detective-agency',
 '1-ladys-detective-agency',
 '1-lifestyle',
 '1-manga-manhwa-manhua-series-done',
 '1-my-ex-collection',
 '1-my-extra-longlist',
 '1-novellas-short-stories-essays',
 '1-of-best-books-ever',
 '1-of-trilogy',
 '1-own',
 '1-owned',
 '1-owned-books',
 '1-owning',
 '1-read-bookshelf',
 '1-read-duplicate',
 '1-star',
 '1-stars',
 '1-stephen-king',
 '1-the-best-to-read',
 '1-to-buy',
 '1-to-read-crime',
 '1-to-sort',
 '1-year-52-plays',
 '1-year-challenge',
 '10',
 '10-aussie-books-to-read-before-you',
 '10-next',
 '10-words-ns',
 '100',
 '100-best-books',
 '100-best-books-of-all-time',
 '100-best-books-of-all-time-the-worl',
 '100-best-business-books',
 '100-best-novels',
 '100-best-novels-list',
 '100-best-novels-modern-library',
 '100-book-challenge',
 '100-books',
 '100-books-bbc',
 '100-books-every-man-should-read',
 '100-books-i-own-for-2017',
 '100-books-that-define-the-00-s',
 '100-books-to-read',
 '100-books-to-read-before-you-die',
 '100-books-to-read-in-a-lifetime',
 '100-books-to-read-my-version',
 '100-bullets',
 '100-children-s-books',
 '100-essential-novels',
 '100-essential-novels-poster',
 '100-fiction',
 '100-greatest',
 '100-greatest-books-ever-written',
 '100-greatest-novels',
 '100-in-100-list',
 '100-modern-library',
 '100-must-read-books',
 '100-must-read-books-the-essential',
 '100-novels-everyone-should-read',
 '100-recommended',
 '100-year-war',
 '100-years-war',
 '1000',
 '1000-book-before-kindergarten',
 '1000-book-goal',
 '1000-books',
 '1000-books-before-kindergarten',
 '1000-books-to-read-before-you-die',
 '1000-by-k',
 '1000-good-books-1-3',
 '1000-harry',
 '1000-novels',
 '1000-plus-pages',
 '1000s-1300s',
 '1001',
 '1001-before-you-die',
 '1001-book',
 '1001-book-list',
 '1001-books',
 '1001-books-2006',
 '1001-books-before-die',
 '1001-books-before-you-die',
 '1001-books-challenge',
 '1001-books-i-have-read',
 '1001-books-list',
 '1001-books-read',
 '1001-books-to-read',
 '1001-books-to-read-before-adult',
 '1001-books-to-read-before-i-die',
 '1001-books-to-read-before-you-die',
 '1001-books-you-must-read',
 '1001-books-you-must-read-b4-you-die',
 '1001-books-you-must-read-before-you',
 '1001-bymrbyd',
 '1001-challenge',
 '1001-children-s-books',
 '1001-children-s-books-you-must-read',
 '1001-childrens-books',
 '1001-comics',
 '1001-import',
 '1001-kids-5plus',
 '1001-kids-8plus',
 '1001-kids-books',
 '1001-libri',
 '1001-libri-da-leggere',
 '1001-list',
 '1001-must-read',
 '1001-must-read-books',
 '1001-must-reads',
 '1001-read',
 '1001-to-read',
 '1001-to-read-before-you-die',
 '1001-unread',
 '1001books',
 '1009',
 '101-bibles-tools',
 '101-books-that-you-must-read-before',
 '101-books-to-read-before-you-die',
 '101-à-lire-dans-sa-vie',
 '101st-airborne',
 '102-miscellaneous',
 '10th-century',
 '10th-grade',
 '10th-grade-advisory',
 '10th-grade-books',
 '10th-grade-reading',
 '11',
 '11-birthdays',
 '11-disabilities',
 '11-in-class',
 '11-november-2014-15-16',
 '110',
 '1100s',
 '111',
 '1111',
 '11th-century',
 '11th-grade',
 '11th-grade-advisory',
 '12',
 '12-dancing-princesses',
 '12-in-series',
 '12-religious',
 '12017',
 '123',
 '123-zzz',
 '12th-century',
 '12th-grade',
 '12th-grade-books',
 '12th-grade-reading',
 '13',
 '13-16',
 '13-25',
 '13-gifts',
 '13-in-series',
 '1395',
 '13th-century',
 '14',
 '14-in-series',
 '1400s',
 '140924-150913-r351',
 '1421',
 '1421-1737',
 '1438-2016',
 '1452-1519',
 '14th',
 '14th-century',
 '14艺术美学',
 '15-16-school-year',
 '15-in-series',
 '15-with-subtitle',
 '15-words-ns',
 '150-best',
 '1500s',
 '150321-160409-r',
 '1507-office',
 '1537-1553',
 '1543',
 '1564-1616',
 '158-1',
 '15th-century',
 '16',
 '1600',
 '1600s',
 '1643-1715',
 '1660s',
 '1665-harvard-grad',
 '16th-18th-century',
 '16th-c',
 '16th-century',
 '16th-century-setting',
 '17',
 '17-children-s-book',
 '17-cottonwood-corner',
 '17-in-series',
 '1700s',
 '1702-1714',
 '1775-1783',
 '1775-1800',
 '1776',
 '1790s',
 '17th-century',
 '17th-century-england',
 '17th-century-germany',
 '18',
 '18-books-every-white-ally-should-re',
 '18-creativity',
 '1800',
 '1800-1900',
 '1800-s-massachusetts',
 '1800s',
 '1812-1870',
 '1820s',
 '1830s',
 '1840s',
 '1844-1900',
 '1850-s',
 '1850s',
 '1851-1900',
 '1854',
 '1860s',
 '1863',
 '187',
 '1870s',
 '1871-1945',
 '1880s',
 '1883-1924',
 '1888-1955',
 '1890s',
 '18th',
 '18th-c',
 '18th-century',
 '18th-century-japan',
 '18th-century-literature',
 '19',
 '19-in-alex-cross-series',
 '1900',
 '1900-s',
 '1900-storm',
 '1900s',
 '1900s-farm-life',
 '1904',
 '1907-sahin-library-Şahİn-kİtapliĞi',
 '1908',
 '1910s',
 '1914',
 '1914-1918',
 '1915',
 '1919',
 '1920-',
 '1920-1930',
 '1920-30-s-british-period-mystery',
 '1920-s',
 '1920s',
 '1920s-1930s',
 '1930-1939',
 '1930-s',
 '1930-s-depression-era',
 '1930-s-great-depression',
 '1930s',
 '1932',
 '1933-and-present-time',
 '1934',
 '1938-hurricane',
 '1939',
 '1939-1945',
 '1940-1945',
 '1940-1949',
 '1940-to-1949',
 '1940s',
 '1940s-britain',
 '1942',
 '1945',
 '1945-',
 '1946',
 '1946-',
 '1948',
 '1948-',
 '1950-s',
 '1950-s-1960-s-childhood',
 '1950-s-english-village-life',
 '1950s',
 '1950s-america',
 '1953-2004',
 '1958',
 '1958-',
 '1959',
 '1960-1969',
 '1960-s',
 '1960s',
 '1960s-counterculture',
 '1960s-women-s-status',
 '1961-1974',
 '1961-1975',
 '1963',
 '1966',
 '1969-1974',
 '1970',
 '1970-1979',
 '1970-s',
 '1970s',
 '1971',
 '1974',
 '1975',
 '1975-1979',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980-1989',
 '1980-s',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1983-2005',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990-1999',
 '1990-s-books',
 '1990s',
 '1991',
 '1992',
 '1992-1993',
 '1992-riots-in-l-a',
 '1993',
 '1993-2001',
 '1994',
 '1994-read-books',
 '1995',
 '1995-read-books',
 '1996',
 '1997',
 '1998',
 '1998-modern-library-100-best',
 '1998-read-books',
 '1999',
 '1999-and-before',
 '1999-books',
 '19th',
 '19th-c',
 '19th-c-philosophy',
 '19th-century',
 '19th-century-american',
 '19th-century-americans-in-paris',
 '19th-century-british',
 '19th-century-british-literature',
 '19th-century-china',
 '19th-century-classics',
 '19th-century-england',
 '19th-century-fairy-tales',
 '19th-century-fiction',
 '19th-century-french-literature',
 '19th-century-history',
 '19th-century-lit',
 '19th-century-literature',
 '1a-toppicks-own',
 '1ab-bookcount-5',
 '1ax-sorting-7-case-7b',
 '1b-wantdigital',
 '1e-toppicks',
 '1k-books-before-kindergarten',
 '1kbbk',
 '1kindle-available',
 '1non-fiction',
 '1overdrive',
 '1postwar379404nf-other',
 '1q84',
 '1rhave',
 '1st',
 '1st-batch',
 '1st-book-of-series',
 '1st-books-or-main-shelf',
 '1st-century-bc',
 '1st-day-of-school',
 '1st-edition',
 '1st-grade',
 '1st-half-of-the-20th-century',
 '1st-in-a-new-trilogy-about-eve-dunc',
 '1st-in-a-series',
 '1st-in-series',
 '1st-joe-pickett',
 '1st-of-series',
 '1st-person-perspective',
 '1st-quarter',
 '1st-sheriff-walt-longmire',
 '1st-term',
 '1st-term-reading',
 '1st-trimester',
 '1st-up',
 '1to-read-to-buy',
 '1y-prayer',
 '1نجوم',
 '2',
 '2-0',
 '2-1-0-e-book',
 '2-5-oitnb-challenge',
 '2-5-stars',
 '2-business',
 '2-copies',
 '2-deadly-wonders-series',
 '2-háló-nagy',
 '2-in-series',
 '2-nah',
 '2-non-fiction',
 '2-read-in-highschool',
 '2-read-owned',
 '2-star',
 '2-stars',
 '2-states',
 '2-very-interested',
 '2-years-old',
 '2-ضباط',
 '20',
 '20-book-challenge',
 '20-books-to-read-in-your-20-s',
 '20-books-to-read-in-your-20s',
 '20-in-series',
 '20-mile-march',
 '20-prey-series',
 '20-s',
 '20-somethings',
 '20-year-old-murder',
 '200',
 '200-300pgs',
 '200-books-to-read-in-your-lifetime',
 '200-pages-or-under',
 '200-religion',
 '200-to-300',
 '200-to-300-pages',
 '2000',
 '2000-2009',
 '2000-2010',
 '2000-2012',
 '2000-2016',
 '2000-s',
 '2000s',
 '2000s-books',
 '2001',
 '2001-',
 '2001-2009',
 '2002',
 '2003',
 '2003-2013',
 '2004',
 '2004-books',
 '2004-read-books',
 '2004-wlt-gift',
 '2005',
 '2005-reads',
 '2006',
 '2006-2009',
 '2006-2010',
 '2006-2011-release',
 '2006-books',
 '2006-reads',
 '2007-2009',
 '2007-reads',
 '2008-2009',
 '2008-2010',
 '2008-before_add',
 '2008-book-challenge',
 '2008-books',
 '2008-broadened-horizons',
 '2008-down-releases',
 '2008-presidential-campaign',
 '2008-read',
 '2008-reads',
 '2008-us-presidential-campaign',
 '2008q1',
 '2009-book-challenge',
 '2009-book-list',
 '2009-books',
 '2009-national-book-award',
 '2009-q1',
 '2009-read',
 '2009-reads',
 '2009-wlt-gift',
 '2009q2',
 '2010-100',
 '2010-2011',
 '2010-2015',
 '2010-and-earlier',
 '2010-book-challenge',
 '2010-book-list',
 '2010-books',
 '2010-books-read',
 '2010-earlier',
 '2010-morrison-library-sale',
 '2010-newbery-award',
 '2010-read',
 '2010-reading-list',
 '2010-reads',
 '2010-release',
 '2010s',
 '2011-2012',
 '2011-2014',
 '2011-alex-award-winner',
 '2011-and-before',
 '2011-and-earlier',
 '2011-books',
 '2011-books-read',
 '2011-newbery-winner',
 '2011-read',
 '2011-reads',
 '2011-release',
 '2011-releases',
 '2012-2013',
 '2012-2013-book-club',
 '2012-2013-first-marking-quarter',
 '2012-2013-fourth-marking-quarter',
 '2012-2013-school-year',
 '2012-2013-second-marking-quarter',
 '2012-2013-third-marking-quarter',
 '2012-40-book-challenge',
 '2012-and-before',
 '2012-and-earlier',
 '2012-book-challenge',
 '2012-book-list',
 '2012-books',
 '2012-books-read',
 '2012-challenge',
 '2012-cover-to-cover',
 '2012-dac',
 '2012-debut-author-challenge',
 '2012-forty-book-challenge',
 '2012-publication',
 '2012-read',
 '2012-reading-challenge',
 '2012-reading-list',
 '2012-readings',
 '2012-reads',
 '2012-release',
 '2012-releases',
 '2012-tournament-of-books',
 '2012-عربي',
 '2013-14',
 '2013-2012',
 '2013-2014',
 '2013-all',
 '2013-and-before',
 '2013-and-earlier',
 '2013-book-challenge',
 '2013-book-list',
 '2013-books',
 '2013-books-read',
 '2013-challenge',
 '2013-debut-author-challenge',
 '2013-favorites',
 '2013-hub-reading-challenge',
 '2013-publication',
 '2013-read',
 '2013-reading-challenge',
 '2013-reading-list',
 '2013-readings',
 '2013-reads',
 '2013-release',
 '2013-releases',
 '2013-third-marking-quarter',
 '2013-tob',
 '2013-tournament-of-books',
 '2014-2',
 '2014-2015',
 '2014-2015-school-year',
 '2014-2016',
 '2014-and-before',
 '2014-book-challenge',
 '2014-book-list',
 '2014-booker-longlist',
 '2014-books',
 '2014-books-completed',
 '2014-books-read',
 '2014-caudill',
 '2014-challenge',
 '2014-favorites',
 '2014-favourites',
 '2014-finished-reading',
 '2014-man-booker',
 '2014-movies',
 '2014-publication',
 '2014-read',
 '2014-read-books',
 '2014-reading-challenge',
 '2014-reading-list',
 '2014-reads',
 '2014-release',
 '2014-releases',
 '2014-to-read',
 '2014-tob',
 '2014-top-20',
 '2014-tournament-of-books',
 '2014-will-robbie-series-3',
 '2014-wom-flipping-the-pages',
 '2015-2',
 '2015-2016',
 '2015-2016-school-year',
 '2015-all-tr177',
 '2015-and-before',
 '2015-book-challenge',
 '2015-books',
 '2015-books-read',
 '2015-books-to-read',
 '2015-caudills',
 '2015-challenge',
 '2015-challenge-books',
 '2015-children-s-literature-2360',
 '2015-en-eerder-gelezen',
 '2015-favorites',
 '2015-jack-reacher-20',
 '2015-list',
 '2015-onwards',
 '2015-or-before',
 '2015-publication',
 '2015-read',
 '2015-reading-challenge',
 '2015-reading-list',
 '2015-reads',
 '2015-release',
 '2015-releases',
 '2015-rmangas-comics',
 '2015-s-readings',
 '2015-summer-reading-list',
 '2015-this-is-now',
 '2015-to-read',
 '2015-tob',
 '2015-tournament-of-books',
 '2016-2017',
 '2016-2017-school-year',
 '2016-52-in-52',
 '2016-60-books',
 '2016-and-before-read-that-i-own',
 '2016-audiobooks',
 '2016-book-challenge',
 '2016-book-club',
 '2016-book-hauls',
 '2016-book-list',
 '2016-book-riot-challenge',
 '2016-booker-longlist',
 '2016-books',
 '2016-books-i-have-read',
 '2016-books-read',
 '2016-botb',
 '2016-challenge',
 '2016-comics',
 '2016-completed',
 '2016-end-of-year-challenge',
 '2016-favorites',
 '2016-favourites',
 '2016-favs',
 '2016-hub-challenge',
 '2016-hub-reading-challenge',
 '2016-list',
 '2016-movies',
 '2016-nora',
 '2016-old-book',
 '2016-publication',
 '2016-read',
 '2016-read-harder',
 '2016-read-harder-challenge',
 '2016-reading',
 '2016-reading-adventure',
 '2016-reading-chalange',
 '2016-reading-challenge',
 '2016-reading-list',
 '2016-reads',
 '2016-release',
 '2016-releases',
 '2016-santiago-read',
 '2016-tbr',
 '2016-to-read',
 '2016-tob',
 '2016-tournament-of-books',
 '2016-vt-reading-challenge',
 '2016-weg',
 '2016-yard-sale',
 '2016_challenge',
 '2017-2',
 '2017-a-z-challenge-friend-f',
 '2017-audio',
 '2017-audio-pdf',
 '2017-audio-read',
 '2017-audiobooks',
 '2017-bbw-dec',
 '2017-best-of',
 '2017-birthday-shelf',
 '2017-book-challenge',
 '2017-book-list',
 '2017-book-riot-read-harder-challeng',
 '2017-books',
 '2017-books-i-read-for-a-challenge-c',
 '2017-books-read',
 '2017-books-to-read',
 '2017-caudill',
 '2017-challenge',
 '2017-chunkster-challenge',
 '2017-comics',
 '2017-favorites',
 '2017-fiction',
 '2017-final',
 '2017-goal',
 '2017-goals',
 '2017-goodreads-challenge',
 '2017-keepers',
 '2017-ku-read',
 '2017-list',
 '2017-log',
 '2017-manga',
 '2017-may-library-book-sale',
 '2017-movies',
 '2017-must-read',
 '2017-need-to-buy',
 '2017-new-age',
 '2017-nora',
 '2017-plan',
 '2017-popsugar-challenge',
 '2017-popsugar-rc',
 '2017-popsugar-reading-challenge',
 '2017-possible-books',
 '2017-potentials',
 '2017-publication',
 '2017-re-read',
 '2017-read',
 '2017-read-books',
 '2017-read-harder-challenge',
 '2017-read-women',
 '2017-reading',
 '2017-reading-challenge',
 '2017-reading-list',
 '2017-reads',
 '2017-release',
 '2017-releases',
 '2017-reread',
 '2017-shelf',
 '2017-summer-reading-list',
 '2017-tbr',
 '2017-to-read',
 '2017-to-read-list',
 '2017-tob',
 '2017-tournament-of-books',
 '2017-want-to-reads',
 '2017_august_horror',
 '2017_horror',
 '2017_horror_tbr_challenge',
 '2017_mount-tbr',
 '2017_reads',
 '2017bookshelf',
 '2017challenge',
 '2017queue',
 '2018',
 '2018-lineup',
 '2018-reads',
 '2020',
 '20s',
 '20th',
 '20th-am',
 '20th-c',
 '20th-century',
 '20th-century-90s',
 '20th-century-america',
 '20th-century-american',
 '20th-century-american-fiction',
 '20th-century-classics',
 '20th-century-drama',
 '20th-century-fiction',
 '20th-century-history',
 '20th-century-lit',
 '20th-century-literature',
 '20th-century-post-ww2',
 '21',
 '21-26-the-blue-hour',
 '21-books-every-woman-should-read',
 '21-in-series',
 '21e',
 '21st',
 '21st-century',
 '21st-century-australian-literature',
 '21st-century-fiction',
 '21st-century-lit',
 '21st-century-skills',
 '21st-century_onward',
 '21th-century',
 '22',
 '22-in-series',
 '22-modern-fantasy',
 '221b',
 '23',
 '23-in-series',
 '23-writing',
 '24',
 '25-books-for-success',
 '25-books-to-read-before-you-die',
 '28',
 '28-books-that-changed-your-life',
 '28-حرف',
 '2b-referenced',
 '2f',
 '2fiction',
 '2gm',
 '2nc',
 '2nd-6th',
 '2nd-century',
 '2nd-chance',
 '2nd-grade',
 '2nd-person',
 '2nd-quarter',
 '2nd-semester',
 '2nd-sequal-to-hatchet',
 '2nd-sheriff-walt-longmire',
 '2nd-to-7th-book-of-series',
 '2nd-trimester',
 '2nd-world-war',
 '2o17-reading-list',
 '2read-graphic-novels',
 '2states',
 '2ضباط',
 '3',
 '3-5',
 '3-5-rating',
 '3-5th-grade',
 '3-bookcount-5',
 '3-considering',
 '3-considering-own',
 '3-deadly-wonders-series',
 '3-fiction',
 '3-food-healthy-life',
 '3-good',
 '3-i-have-not-read',
 '3-in-series',
 '3-kindle',
 '3-lang-english',
 '3-less-star',
 '3-mistake',
 '3-mistakes',
 ...]

### Data Set "Ratings"

In [7]:
data4 = pd.read_csv(r'data/ratings.csv')
ratings = pd.DataFrame(data4)
ratings.head()

   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

### Data Set "to_read"

In [8]:
data5 = pd.read_csv(r'data/to_read.csv')
to_read = pd.DataFrame(data5)
to_read.head()

   user_id  book_id
0        1      112
1        1      235
2        1      533
3        1     1198
4        1     1874

### Data Set "Top 100 Books"

In [21]:
data6 = pd.read_csv('data/top_100_books.csv', encoding = "ISO-8859-1")
top100 = pd.DataFrame(data6)
top100.head()

,idx,rank2,book2,author2,ratings2,reviews2,type2,price2
0,1,1,Becoming,Michelle Obama,4.9,13347,Hardcover,17.95
1,2,2,"Girl, Wash Your Face",Rachel Hollis,4.6,10521,Hardcover,13.63
2,3,3,The Wonky Donkey,Craig Smith,4.7,5503,Paperback,4.99
3,4,4,Fire and Fury,Michael Wolff,4.2,9931,Hardcover,15.57
4,5,5,Fear,Bob Woodward,4.5,3220,Hardcover,15.47

### Data Set "NYT Bestsellers"

In [17]:
data7 = pd.read_csv('data/nyt_bestsellers.csv', encoding = "ISO-8859-1").drop(columns='Unnamed: 0')

nyt_bestsellers = pd.DataFrame(data7)
nyt_bestsellers.head()

                                        book_name     genre
0     I Love Dad with The Very Hungry Caterpillar  children
1                The Wonderful Things You Will Be  children
2  Dr. Seuss's I Love Pop!: A Celebration of Dads  children
3                              Dragons Love Tacos  children
4                        How to Babysit a Grandpa  children

In [22]:
nyt_bestsellers.genre.unique()

array(['children', 'fiction', 'non-fiction', 'misc', 'young_adult'],
      dtype=object)