In [19]:
import pandas as pd
import re

In [20]:
dow = pd.read_csv("data/DJI-2.csv", sep=";")
twitter = pd.read_csv("data/tweets_clean.csv", sep=";", index_col="Unnamed: 0")

In [21]:
dow.head(30)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-01-04,"10430,690430","10604,969727","10430,690430","10583,959961","10583,959961",179780000
1,2010-01-05,"10584,559570","10584,559570","10522,519531","10572,019531","10572,019531",188540000
2,2010-01-06,"10564,719727","10594,990234","10546,549805","10573,679688","10573,679688",186040000
3,2010-01-07,"10571,110352","10612,370117","10505,209961","10606,860352","10606,860352",217390000
4,2010-01-08,"10606,400391","10619,400391","10554,330078","10618,190430","10618,190430",172710000
5,2010-01-11,"10620,309570","10676,230469","10591,589844","10663,990234","10663,990234",182050000
6,2010-01-12,"10662,860352","10663,080078","10568,839844","10627,259766","10627,259766",256050000
7,2010-01-13,"10628,089844","10709,259766","10614,490234","10680,769531","10680,769531",202810000
8,2010-01-14,"10680,160156","10723,769531","10666,860352","10710,549805","10710,549805",201320000
9,2010-01-15,"10706,990234","10709,940430","10561,059570","10609,650391","10609,650391",362930000
10,2010-01-19,"10608,370117","10729,889648","10591,969727","10725,429688","10725,429688",192150000
11,2010-01-20,"10719,690430","10719,919922","10517,299805","10603,150391","10603,150391",203270000
12,2010-01-21,"10603,910156","10614,940430","10374,690430","10389,879883","10389,879883",304290000
13,2010-01-22,"10389,580078","10389,580078","10157,639648","10172,980469","10172,980469",323620000
14,2010-01-25,"10175,099609","10256,870117","10171,769531","10196,860352","10196,860352",215330000
15,2010-01-26,"10195,349609","10285,129883","10155,599609","10194,290039","10194,290039",217300000
16,2010-01-27,"10194,290039","10255,059570","10104,360352","10236,160156","10236,160156",262170000
17,2010-01-28,"10236,919922","10258,830078","10055,080078","10120,459961","10120,459961",240050000
18,2010-01-29,"10122,040039","10239,339844","10043,750000","10067,330078","10067,330078",316900000
19,2010-02-01,"10068,990234","10190,889648","10068,910156","10185,530273","10185,530273",198430000
20,2010-02-02,"10186,129883","10314,839844","10173,589844","10296,849609","10296,849609",237140000
21,2010-02-03,"10291,730469","10307,200195","10231,929688","10270,549805","10270,549805",198940000
22,2010-02-04,"10273,120117","10273,120117","9998,030273","10002,179688","10002,179688",304240000
23,2010-02-05,"10003,690430","10031,959961","9835,089844","10012,230469","10012,230469",308320000
24,2010-02-08,"10005,429688","10028,559570","9904,089844","9908,389648","9908,389648",216270000
25,2010-02-09,"9910,280273","10139,429688","9910,059570","10058,639648","10058,639648",236210000
26,2010-02-10,"10055,459961","10085,540039","9962,959961","10038,379883","10038,379883",178600000
27,2010-02-11,"10037,849609","10161,570313","9976,709961","10144,190430","10144,190430",194470000
28,2010-02-12,"10137,230469","10137,389648","9983,820313","10099,139648","10099,139648",296510000
29,2010-02-16,"10100,809570","10279,540039","10100,809570","10268,809570","10268,809570",234900000

In [22]:
def month_finder(row):
    return re.findall(r"(\d{4}-\d{2})-\d{2}", row["Date"])[0]
dow['Month'] = dow.apply(month_finder, axis=1)

In [23]:
dow_peaks = pd.DataFrame(dow.groupby("Month", as_index = False).aggregate({"Low":"min", "High":"max"}))

In [24]:
dow_peaks

       Month           Low          High
0    2010-01  10043,750000  10729,889648
1    2010-02  10068,910156  10438,549805
2    2010-03  10326,099609  10955,480469
3    2010-04  10844,089844  11258,009766
4    2010-05  10052,669922  11177,669922
..       ...           ...           ...
122  2020-03  18213,650391  27102,339844
123  2020-04  20735,019531  24764,769531
124  2020-05  22789,619141  25758,789063
125  2020-06  24843,179688  27580,210938
126  2020-07  25523,509766  26297,529297

[127 rows x 3 columns]

In [25]:
dow_peaks["High_date"] = ""
dow_peaks["Low_date"] = ""
for i in range(len(dow_peaks)):
    low = dow.loc[(dow_peaks["Low"][i]==dow["Low"], "Date")]
    high = dow.loc[(dow_peaks["High"][i]==dow["High"], "Date")]
    dow_peaks["Low_date"][i] = (re.findall(r"\d{4}-\d{2}-\d{2}", str(low)))[0]
    dow_peaks["High_date"][i] = (re.findall(r"\d{4}-\d{2}-\d{2}", str(high)))[0]

In [26]:
twitter.loc[dow_peaks["Low_date"][100]==twitter["YYYY-MM-DD"]].loc[34082, "link"]

'https://twitter.com/realDonaldTrump/status/991992302267785216'

In [27]:
test = twitter.loc[dow_peaks["Low_date"][0]==twitter["YYYY-MM-DD"]].index
len(test)

0

In [28]:
test = []
len(test)

0

In [29]:
twitter["YYYY-MM-DD"]

0        2009-05-04
1        2009-05-04
2        2009-05-08
3        2009-05-08
4        2009-05-12
            ...
43347    2020-06-17
43348    2020-06-17
43349    2020-06-17
43350    2020-06-17
43351    2020-06-17
Name: YYYY-MM-DD, Length: 43352, dtype: object

In [30]:
twitter.loc[dow_peaks["Low_date"][100]==twitter["YYYY-MM-DD"]].index

Int64Index([34082, 34083, 34084, 34085, 34086, 34087], dtype='int64')

In [31]:
links_list_low =twitter.loc[dow_peaks["Low_date"][100]==twitter["YYYY-MM-DD"]].index

In [32]:
links_list_low = twitter.loc[dow_peaks["Low_date"][100]==twitter["YYYY-MM-DD"]].loc[links_list_low[1], "link"]

In [33]:
dow_peaks["high_tweet_links"] = ""
dow_peaks["low_tweet_links"] = ""

for i in range(len(dow_peaks)):
    index_list_low = twitter.loc[dow_peaks["Low_date"][i]==twitter["YYYY-MM-DD"]].index
    links_list_low = []
    index_list_high = twitter.loc[dow_peaks["High_date"][i]==twitter["YYYY-MM-DD"]].index
    links_list_high = []
    if len(index_list_low)>0:
        for j in range(len(index_list_low)):
            links_list_low.append(twitter.loc[dow_peaks["Low_date"][i]==twitter["YYYY-MM-DD"]].loc[index_list_low[j], "link"])
            dow_peaks["low_tweet_links"][i] = links_list_low
    else:
        dow_peaks["low_tweet_links"][i] = "No tweets today!"
    if len(index_list_high)>0:
        for k in range(len(index_list_high)):
            links_list_high.append(twitter.loc[dow_peaks["High_date"][i]==twitter["YYYY-MM-DD"]].loc[index_list_high[k], "link"])
            dow_peaks["high_tweet_links"][i] = links_list_high
    else:
        dow_peaks["high_tweet_links"][i] = "No tweets today!"

        
dow_peaks

,Month,Low,High,High_date,Low_date,high_tweet_links,low_tweet_links
0,2010-01,"10043,750000","10729,889648",2010-01-19,2010-01-29,No tweets today!,No tweets today!
1,2010-02,"10068,910156","10438,549805",2010-02-19,2010-02-01,No tweets today!,No tweets today!
2,2010-03,"10326,099609","10955,480469",2010-03-25,2010-03-01,No tweets today!,No tweets today!
3,2010-04,"10844,089844","11258,009766",2010-04-26,2010-04-08,[https://twitter.com/realDonaldTrump/status/12...,No tweets today!
4,2010-05,"10052,669922","11177,669922",2010-05-03,2010-05-24,[https://twitter.com/realDonaldTrump/status/13...,[https://twitter.com/realDonaldTrump/status/14...
...,...,...,...,...,...,...,...
122,2020-03,"18213,650391","27102,339844",2020-03-04,2020-03-23,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
123,2020-04,"20735,019531","24764,769531",2020-04-29,2020-04-02,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
124,2020-05,"22789,619141","25758,789063",2020-05-28,2020-05-14,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
125,2020-06,"24843,179688","27580,210938",2020-06-08,2020-06-15,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
126,2020-07,"25523,509766","26297,529297",2020-07-06,2020-07-09,No tweets today!,No tweets today!

In [55]:
presidential_dow_peaks = dow_peaks[-43:]
presidential_dow_peaks = presidential_dow_peaks.reset_index()
presidential_dow_peaks

,index,Month,Low,High,High_date,Low_date,high_tweet_links,low_tweet_links
0,84,2017-01,"19677,939453","20125,580078",2017-01-26,2017-01-19,[https://twitter.com/realDonaldTrump/status/82...,[https://twitter.com/realDonaldTrump/status/82...
1,85,2017-02,"19831,089844","20851,330078",2017-02-27,2017-02-02,[https://twitter.com/realDonaldTrump/status/83...,[https://twitter.com/realDonaldTrump/status/82...
2,86,2017-03,"20412,800781","21169,109375",2017-03-01,2017-03-27,[https://twitter.com/realDonaldTrump/status/83...,[https://twitter.com/realDonaldTrump/status/84...
3,87,2017-04,"20379,550781","21070,900391",2017-04-26,2017-04-19,[https://twitter.com/realDonaldTrump/status/85...,[https://twitter.com/realDonaldTrump/status/85...
4,88,2017-05,"20553,449219","21112,320313",2017-05-25,2017-05-18,[https://twitter.com/realDonaldTrump/status/86...,[https://twitter.com/realDonaldTrump/status/86...
5,89,2017-06,"20994,220703","21535,029297",2017-06-20,2017-06-01,[https://twitter.com/realDonaldTrump/status/87...,[https://twitter.com/realDonaldTrump/status/87...
6,90,2017-07,"21279,300781","21929,800781",2017-07-31,2017-07-11,[https://twitter.com/realDonaldTrump/status/89...,[https://twitter.com/realDonaldTrump/status/88...
7,91,2017-08,"21600,339844","22179,109375",2017-08-08,2017-08-21,[https://twitter.com/realDonaldTrump/status/89...,[https://twitter.com/realDonaldTrump/status/89...
8,92,2017-09,"21709,630859","22419,509766",2017-09-21,2017-09-05,[https://twitter.com/realDonaldTrump/status/91...,[https://twitter.com/realDonaldTrump/status/90...
9,93,2017-10,"22416,000000","23485,250000",2017-10-24,2017-10-02,[https://twitter.com/realDonaldTrump/status/92...,[https://twitter.com/realDonaldTrump/status/91...
10,94,2017-11,"23242,750000","24327,820313",2017-11-30,2017-11-15,[https://twitter.com/realDonaldTrump/status/93...,[https://twitter.com/realDonaldTrump/status/93...
11,95,2017-12,"23921,900391","24876,070313",2017-12-18,2017-12-01,[https://twitter.com/realDonaldTrump/status/94...,[https://twitter.com/realDonaldTrump/status/93...
12,96,2018-01,"24741,699219","26616,710938",2018-01-26,2018-01-02,[https://twitter.com/realDonaldTrump/status/95...,[https://twitter.com/realDonaldTrump/status/94...
13,97,2018-02,"23360,289063","26306,699219",2018-02-01,2018-02-09,[https://twitter.com/realDonaldTrump/status/95...,[https://twitter.com/realDonaldTrump/status/96...
14,98,2018-03,"23509,060547","25449,150391",2018-03-12,2018-03-23,[https://twitter.com/realDonaldTrump/status/97...,[https://twitter.com/realDonaldTrump/status/97...
15,99,2018-04,"23344,519531","24858,970703",2018-04-17,2018-04-02,[https://twitter.com/realDonaldTrump/status/98...,[https://twitter.com/realDonaldTrump/status/98...
16,100,2018-05,"23531,310547","25086,490234",2018-05-21,2018-05-03,[https://twitter.com/realDonaldTrump/status/99...,[https://twitter.com/realDonaldTrump/status/99...
17,101,2018-06,"23997,210938","25402,830078",2018-06-11,2018-06-28,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
18,102,2018-07,"24077,560547","25587,240234",2018-07-26,2018-07-02,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
19,103,2018-08,"24965,769531","26167,939453",2018-08-29,2018-08-15,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
20,104,2018-09,"25754,320313","26769,160156",2018-09-21,2018-09-11,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
21,105,2018-10,"24122,230469","26951,810547",2018-10-03,2018-10-29,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
22,106,2018-11,"24268,740234","26277,820313",2018-11-08,2018-11-23,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
23,107,2018-12,"21712,529297","25980,210938",2018-12-03,2018-12-26,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
24,108,2019-01,"22638,410156","25109,619141",2019-01-30,2019-01-03,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
25,109,2019-02,"24883,039063","26241,419922",2019-02-25,2019-02-08,[https://twitter.com/realDonaldTrump/status/10...,[https://twitter.com/realDonaldTrump/status/10...
26,110,2019-03,"25208,000000","26155,980469",2019-03-04,2019-03-11,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
27,111,2019-04,"26062,589844","26695,960938",2019-04-23,2019-04-11,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
28,112,2019-05,"24809,509766","26689,390625",2019-05-01,2019-05-31,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
29,113,2019-06,"24680,570313","26907,369141",2019-06-21,2019-06-03,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
30,114,2019-07,"26616,210938","27398,679688",2019-07-16,2019-07-01,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
31,115,2019-08,"25339,599609","27175,589844",2019-08-01,2019-08-15,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
32,116,2019-09,"25978,220703","27306,730469",2019-09-12,2019-09-03,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
33,117,2019-10,"25743,460938","27204,359375",2019-10-30,2019-10-03,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
34,118,2019-11,"27142,949219","28174,970703",2019-11-27,2019-11-01,[https://twitter.com/realDonaldTrump/status/11...,[https://twitter.com/realDonaldTrump/status/11...
35,119,2019-12,"27325,130859","28701,660156",2019-12-27,2019-12-03,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
36,120,2020-01,"28169,529297","29373,619141",2020-01-17,2020-01-31,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
37,121,2020-02,"24681,009766","29568,570313",2020-02-12,2020-02-28,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
38,122,2020-03,"18213,650391","27102,339844",2020-03-04,2020-03-23,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
39,123,2020-04,"20735,019531","24764,769531",2020-04-29,2020-04-02,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
40,124,2020-05,"22789,619141","25758,789063",2020-05-28,2020-05-14,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
41,125,2020-06,"24843,179688","27580,210938",2020-06-08,2020-06-15,[https://twitter.com/realDonaldTrump/status/12...,[https://twitter.com/realDonaldTrump/status/12...
42,126,2020-07,"25523,509766","26297,529297",2020-07-06,2020-07-09,No tweets today!,No tweets today!

In [79]:
presidential_dow_peaks.loc[presidential_dow_peaks["Month"]=="2020-04"].index
presidential_dow_peaks["high_tweet_links"][39]

['https://twitter.com/realDonaldTrump/status/1255484391364665351',
 'https://twitter.com/realDonaldTrump/status/1255507868280856581',
 'https://twitter.com/realDonaldTrump/status/1255510996623527936',
 'https://twitter.com/realDonaldTrump/status/1255656645759246341',
 'https://twitter.com/realDonaldTrump/status/1255657225659523072',
 'https://twitter.com/realDonaldTrump/status/1255661296047067138',
 'https://twitter.com/realDonaldTrump/status/1255696235970940934',
 'https://twitter.com/realDonaldTrump/status/1255706636972363776',
 'https://twitter.com/realDonaldTrump/status/1255708741950943233',
 'https://twitter.com/realDonaldTrump/status/1255710938075889664',
 'https://twitter.com/realDonaldTrump/status/1255714490554953736',
 'https://twitter.com/realDonaldTrump/status/1255718837762306049']

In [36]:
presidential_dow_peaks.to_csv('data/presidential_dow_peaks.csv', sep = ';')