In [2]:
import pandas as pd
import requests

In [30]:
temperatures = pd.read_csv('temperatures.csv', sep=';')
temperatures.dtypes

Year              int64
No_Smoothing    float64
Lowess(5)       float64
dtype: object

In [45]:
animals = pd.read_excel('../Mireia/animals.xlsx')

#animals.astype({'Year': 'int64'}).dtypes

animals['Year'][animals['Year'] == '1996 _1998'] = 1998

animals

/home/linuxbrew/.linuxbrew/Cellar/jupyterlab/2.0.1/libexec/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Year,Assessment,Mammals,Birds,Reptiles,Amphibians,Fishes,Subtotal\n(Vertebrates),Insects,Molluscs,...,Gymnosperms,Flowering\nplants,Green\nalgae,Red\nalgae,Subtotal\n(Plants),Lichens,Mushrooms,Brown\nalgae,Subtotal\n(Fungi & protists),TOTAL
0,2020,Total assessed,5.899,11.147,7.833,6.892,20.878,52.649,9.793,8.772,...,1.015,41.516,16,58,43.557,30,313,15,358,120.372
1,2020,Total threatened,1.299,1.486,1.406,2.276,2.849,9.316,1.819,2.275,...,402.000,16.667,0,9,17.507,27,166,6,199,32.441
2,2019,Total assessed,5.850,11.147,7.829,6.794,19.199,50.819,8.696,8.749,...,1.014,36.623,13,58,38.630,27,253,15,295,112.432
3,2019,Total threatened,1.244,1.486,1.409,2.200,2.674,9.013,1.647,2.250,...,402.000,14.938,0,9,15.774,24,140,6,170,30.178
4,2018,Total assessed,5.692,11.126,7.127,6.722,16.803,47.470,8.037,8.627,...,1.012,25.771,13,58,27.514,23,43,15,81,96.951
5,2018,Total threatened,1.219,1.492,1.307,2.092,2.332,8.442,1.537,2.195,...,401.000,12.564,0,9,13.299,20,33,6,59,26.840
6,2017,Total assessed,5.674,11.122,6.278,6.609,16.409,46.092,7.639,8.413,...,1.012,22.566,13,58,24.230,13,43,15,71,91.523
7,2017,Total threatened,1.204,1.469,1.215,2.100,2.386,8.374,1.414,2.187,...,401.000,11.773,0,9,12.505,10,33,6,49,25.821
8,2016,Total assessed,5.567,11.121,5.338,6.534,16.134,44.694,6.587,7.276,...,1.011,20.652,13,58,22.253,8,25,15,48,85.604
9,2016,Total threatened,1.194,1.460,1.079,2.068,2.359,8.160,1.268,1.984,...,400.000,10.941,0,9,11.643,7,21,6,34,24.307
10,2015,Total assessed,5.502,10.424,4.669,6.460,14.462,41.517,5.573,7.216,...,1.011,19.206,13,58,20.755,9,25,15,49,79.837
11,2015,Total threatened,1.197,1.375,944.000,1.994,2.271,7.781,1.046,1.950,...,400.000,10.551,0,9,11.233,7,22,6,35,23.250
12,2014,Total assessed,5.513,10.425,4.414,6.414,12.457,39.223,5.304,7.217,...,1.010,18.195,13,58,19.738,4,1,15,20,76.199
13,2014,Total threatened,1.199,1.373,927.000,1.957,2.222,7.678,993.000,1.950,...,400.000,9.905,0,9,10.584,4,1,6,11,22.413
14,2013,Total assessed,5.506,10.065,4.204,6.409,11.172,37.356,4.610,6.809,...,1.010,16.766,13,58,18.291,2,1,15,18,71.576
15,2013,Total threatened,1.143,1.308,879.000,1.950,2.110,7.390,896.000,1.898,...,399.000,9.394,0,9,10.065,2,1,6,9,21.286
16,2012,Total assessed,5.501,10.064,3.755,6.374,10.590,36.284,4.003,6.183,...,1.012,14.178,13,58,15.674,2,1,15,18,65.518
17,2012,Total threatened,1.139,1.313,807.000,1.933,2.058,7.250,829.000,1.857,...,374.000,8.764,0,9,9.390,2,1,6,9,20.219
18,2011,Total assessed,5.499,10.052,3.336,6.338,9.554,34.779,3.844,5.422,...,1.020,12.994,13,58,14.496,2,1,15,18,61.914
19,2011,Total threatened,1.138,1.253,772.000,1.917,2.028,7.108,741.000,1.673,...,377.000,8.527,0,9,9.156,2,1,6,9,19.570
20,2010,Total assessed,5.491,10.027,2.806,6.296,8.848,33.468,3.269,3.149,...,926.000,11.584,2,58,12.914,2,1,15,18,55.926
21,2010,Total threatened,1.131,1.240,594.000,1.898,1.851,6.714,733.000,1.288,...,371.000,8.116,0,9,8.724,2,1,6,9,18.351
22,2009,Total assessed,5.490,9.998,1.677,6.285,4.443,27.893,2.619,2.306,...,909.000,10.876,2,58,12.151,2,1,15,18,47.677
23,2009,Total threatened,1.142,1.223,469.000,1.895,1.414,6.143,711.000,1.036,...,322.000,7.948,0,9,8.500,2,1,6,9,17.291
24,2008,Total assessed,5.488,9.990,1.385,6.260,3.481,26.604,1.259,2.212,...,910.000,10.779,2,58,12.055,2,1,15,18,44.838
25,2008,Total threatened,1.141,1.222,423.000,1.905,1.275,5.966,626.000,978.000,...,323.000,7.904,0,9,8.457,2,1,6,9,16.928
26,2007,Total assessed,4.863,9.956,1.385,5.915,3.119,25.238,1.255,2.212,...,909.000,10.771,2,58,12.043,2,1,15,18,41.415
27,2007,Total threatened,1.094,1.217,422.000,1.808,1.201,5.742,623.000,978.000,...,321.000,7.899,0,9,8.447,2,1,6,9,16.306
28,2006,Total assessed,4.864,9.934,664.000,5.918,2.912,24.292,1.192,2.163,...,908.000,10.688,0,0,11.901,2,1,0,3,40.174
29,2006,Total threatened,1.093,1.206,341.000,1.811,1.171,5.622,623.000,975.000,...,306.000,7.865,0,0,8.390,2,1,0,3,16.116
30,2004,Total assessed,4.853,9.917,499.000,5.743,1.721,22.733,771.000,2.163,...,907.000,10.614,0,0,11.824,2,0,0,2,38.046
31,2004,Total threatened,1.101,1.213,304.000,1.770,800.000,5.188,559.000,974.000,...,305.000,7.796,0,0,8.321,2,0,0,2,15.503
32,2003,Total assessed,4.789,2.139,473.000,401.000,1.532,9.334,768.000,2.098,...,907.000,8.526,0,0,9.706,2,0,0,2,22.424
33,2003,Total threatened,1.130,1.194,293.000,157.000,750.000,3.524,553.000,967.000,...,304.000,6.279,0,0,6.774,2,0,0,2,12.259
34,2002,Total assessed,2.150,2.138,453.000,263.000,1.265,6.269,747.000,2.018,...,251.000,6.816,0,0,7.150,0,0,0,0,16.697
35,2002,Total threatened,1.137,1.192,293.000,157.000,742.000,3.521,557.000,939.000,...,142.000,5.492,0,0,5.714,0,0,0,0,11.167
36,2000,Total assessed,2.133,2.123,454.000,231.000,1.267,6.208,747.000,2.017,...,251.000,6.688,0,0,7.022,0,0,0,0,16.507
37,2000,Total threatened,1.130,1.183,296.000,146.000,752.000,3.507,555.000,938.000,...,141.000,5.390,0,0,5.611,0,0,0,0,11.046
38,1998,Total assessed,2.067,2.167,428.000,198.000,1.194,6.054,730.000,1.958,...,NaN,NaN,0,0,NaN,0,0,0,0,NaN
39,1998,Total threatened,1.096,1.107,253.000,124.000,734.000,3.314,537.000,920.000,...,142.000,5.186,0,0,5.328,0,0,0,0,10.533

In [32]:
population = pd.read_csv('../Carles_part/population_data.csv', header=1)
population.dtypes

Year                                                      int64
Population, total                                       float64
Population ages 0-14 (% of total population)            float64
Population ages 15-64 (% of total population)           float64
Population ages 65 and above (% of total population)    float64
dtype: object

In [8]:
f = pd.read_csv('animals_population_temperature.csv')

df = f[['Year','Subtotal\n(Vertebrates)','Subtotal\n(Invertebrates)', 'Subtotal\n(Plants)','TOTAL']]


l_total = []
l_vert = []
l_inv = []
l_plants = []
for i in df['Year']:
    a,t = df[df['Year']==i]['TOTAL']
    l_total.append(t/a)
    
    a,t = df[df['Year']==i]['Subtotal\n(Invertebrates)']
    l_inv.append(t/a)

    a,t = df[df['Year']==i]['Subtotal\n(Plants)']
    l_plants.append(t/a)
    
    
    a,t = df[df['Year']==i]['Subtotal\n(Vertebrates)']
    l_vert.append(t/a)
    

f['Index_total'] = l_total
f['Index_vert'] = l_vert
f['Index_inv'] = l_inv
f['Index_plants'] = l_plants


f.to_csv('apt_full_indexed.csv', index=False)